### ISSUE TITLE
Pótlás

### ISSUE THREAD

**Issue by oliverosz** [pancloudy/Tabkezelo#2]
- GHA worflow
- Doxygen
- Memtest/unit test

**Comment by tothrobi** [comment]
Jó estét! Tanár Úr még szükségünk lenne egy kis időre.

**Comment by tothrobi** [comment]
Épp a memtest vége fele járunk, de egy 10 percen belül az is meglesz.

**Comment by tothrobi** [comment]
Elvileg a memtest is lefutott és nem jelzett szivárgást.
